# We can join the sets by union function and update fuctions
print("    Adding by Union Function ")
print()
a={1,2,3,4}
nam={"Ali","moni","Kamal","Jamal"}
UI=a.union(nam)
print(UI)
print()
print("   Adding by Update Function ")
print()
a.update(nam)
print(a)
print()
print("   Some important Functions ")
print()
print("   Intersection Functions       ")
print()
a={1,2,3,4,5}
b={3,4,5,6,7}
z=a.intersection(b)
print(z)
print()
print("    Differnce Function     ")
print()
z=a.difference(b)
print(z)
print()
print("    Subset Function    ")
print()
z=a .issubset(b)
print(z)
print()
print("    Superset Functions ")
z=a.issuperset(b)
print(z)
print()
print("    Disjoint Functions  ")
z=a.isdisjoint(b)
print(z)