x=[20,30,"Ali",50.5,"Moni",75.2]  
print("       Printing Whole List                   ")
print("                                             ")
print(x)
print("                                              ")
print("       Memory Location Before Modifying       ")
print(id(x))
print("                                             ")
print("       Accesing the List using Index         ")
print("                                             ")
print(x[0])
print(x[1])
print(x[2])
print(x[3])
print(x[4])
print(x[5])
print("                                              ")
print("     Accesing the List using Negative Index   ")
print("                                              ")
print(x[-1])
print(x[-2])
print(x[-3])
print(x[-4])
print(x[-5])
print(x[-6])
print("                                              ")
print("    Modifying The List                        ")
print("                                              ")
x[2]="Mudasir"
print(x)
print("                                              ")
print("       Memory Location After Modifying        ")
print("                                              ")
print(id(x))

