x=3
y=3.5
z="5"
print("   The original Values are ")
print(x)
print(y)
print(z)
print( "  Casting in Integer data types    ")
x=int(3)
y=int(3.5)
z=int("5")
print(x)
print(y)
print(z)
print( "               ")
print( "  Casting in Float data types      ")
x=float(3)
y=float(3.5)
z=float("5")
print(x)
print(y)
print(z)
print("                ")
print( "  Casting in String data types      ")
x=str(3)
y=str(3.5)
z=str("5")
print(x)
print(y)
print(z)