x=" Hi! Everyone "
print("        Slicing The Strings          ")
print("                                      ")
print(x[0:13])
print("                                      ")
print("        If Starting Position is not defined it will start from 0 index ")
print("                                      ")
print(x[:13])
print("                                      ")
print("        If Ending Position is not defined it will start from starting index to end ")
print("                                      ")
print(x[0:])
print("                                      ")
print("        Modifying The Strings         ")
print("                                      ")
print("        Upper Class                   ")
print("                                      ")
print(x.upper())
print("                                      ")
print("        Lower Class                   ")
print("                                      ")
print(x.lower())
print("                                      ")
print("        Replacing Letters             ")
print("                                      ")
print(x.replace("E","e"))
print("        Split Strings                 ")
print("                                      ")
print(x.split(" , "))
print("                                      ")
print("         Thanks Program Ended         ")


